version: "3.7"

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
          POSTGRES_PASSWORD: mypass
          PGDATA: /data/postgres
        volumes:
           - postgres:/data/postgres
           - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
          - "5431:5432"
        networks:
          - postgres
        restart: unless-stopped
    #    command:
#      -

networks:
    postgres:
        driver: bridge

volumes:
    postgres: