version: "3.7"

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_PASSWORD: mypass
            PGDATA: /data/postgres
        volumes:
           - postgres:/data/postgres
           - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
          - "5431:5432"
        networks:
          - postgres
        restart: unless-stopped
    pyspark:
        image: jupyter/pyspark-notebook:latest
        environment:
            JUPYTER_ENABLE_LAB: "yes"
        ports:
          - "8888:8888"
        volumes:
          - ./data:/home/jovyan/work


networks:
    postgres:
        driver: bridge

volumes:
    postgres: